theme_color:
  primary: indigo
  accent: deep-orange

notice: '欢迎来到本站 , 长按页面顶部可切换网页模式...'

favicon: /images/favicon.jpg
banner: /images/banner.jpg
avatar: /images/avatar.jpeg
rss: /atom.xml

email: jerryweblee@outlook.com
sns:
  twitter:
  facebook:
  google_plus:
  weibo: https://m.weibo.cn/
  instagram:
  tumblr:
  github: https://github.com/JerryWebLee
  linkedin:
  zhihu: https://www.zhihu.com/
  douban: https://www.douban.com/
  qq: 
  wechat:

open_graph:
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification:
  google:
  baidu:
analytics:
  google_site_id:
  baidu_site_id:
  cnzz_site_id:

pages:
- name: 时间轴
  link: /timeline
- name: 标签云
  link: /tagcloud
- name: 相册
  link: /gallery
links:

since: 2021
footer_text:
license:

gallery:
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
  lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi:
  site: true
  page: true
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode:
  caption: 发送到手机
  use: plugin
donate:
search:
  placeholder: 请输入关键字
  path: /search.xml
  use: plugin
local_search:
  enable: true
comment:
  use: valine
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  gitalk_sid_type:
  livere_data_uid:
  valine_leancloud_app_id: oAW1x27e1mh2AsPu7AumBdyx-gzGzoHsz
  valine_leancloud_app_key: sHC6RKIoiQa0mw4L7ixilf4q
  valine_admin_email_hash:
  valine_placeholder: "期待留下你的评论!!(可以使用md格式)"
  valine_page_size: 5
  valine_max_nest: 4,
  valine_avatar: identicon 
  valine_lang: zh-cn
  valine_guest_info: nick,mail
  valine_notify: false
  valine_verify: false
  valine_sid_type:
  valine_count: true
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
